### ISSUE TITLE
Endpoint que retorna alunos de um determinado programa de pós-graduação

### ISSUE THREAD

**Issue by ezanon** [uspdev/replicado-ws#16]

**Comment by masakik** [comment]
Acho que a gente precisar padronizar se var usar CamelCase ou snake_case

**Comment by alecostaweb** [comment]
camelCase
PascalCase (minha preferência)
snake_case
kebab-case

**Comment by ezanon** [comment]
Como entrei há pouco no Uspdev, não vi se vocês já tinham uma
padronização.. Tem?
Devo alterar o código que fiz?
Eu gosto de camelCase, acho que perceberam kkkk


Em ter, 15 de out de 2019 às 17:06, Alessandro Costa de Oliveira <
notifications@github.com> escreveu:
