### ISSUE TITLE
Trazer docentes aposentados

### ISSUE THREAD

**Issue by kawanks** [uspdev/replicado-ws#29]
Trazer docentes aposentados no endpoint `/pessoa/aposentados/docentes`.

**Comment by masakik** [comment]
Ola, não seria melhor usar a url /pessoa/docente/senior? Pois não irá retornar todos os aposentados.

**Comment by alecostaweb** [comment]
Sim. Neste caso seguindo os outros endpoints já criados ficaria:
'/pessoa/docentes/seniores'
@kawanks pode mandar outro commit com esta alteração
